databases:
  - name: franckblog
    databaseName: franckblog
    user: franckblog_user
    plan: free

services:
  - type: web
    name: blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: franckblog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      
